# Generated by Django 3.1.7 on 2021-09-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titleid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='webtoon',
            name='rate',
            field=models.FloatField(),
        ),
    ]
