# Generated by Django 3.1.7 on 2021-09-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20210902_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='titleid',
            name='day',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='titleid',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
