# Generated by Django 3.1.7 on 2021-09-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20210902_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificWebtoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('best_comment', models.CharField(max_length=5000)),
                ('star_point', models.FloatField()),
            ],
        ),
    ]
