# Generated by Django 3.1.7 on 2021-09-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_specificwebtoon'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificwebtoon',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='specificwebtoon',
            name='best_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
