# Generated by Django 3.1.7 on 2021-09-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20210902_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_comment', models.CharField(max_length=5000)),
            ],
        ),
        migrations.RemoveField(
            model_name='specificwebtoon',
            name='best_comment',
        ),
    ]
